jama:
  image: s4nchez/jama:spring2015
  ports:
   - "8080:8080"
  links:
   - jamadb
jamadb:
  image: mysql:5.5.45
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: contour
   MYSQL_USER: jama
   MYSQL_PASSWORD: jama
